version: "3.7"
services:
  server:
    build: .
    image: glitchy/eddc:dev
    restart: unless-stopped
    user: 65534:65534
    ports:
      - 0.0.0.0:31337:31337/tcp
    cap_drop:
      - ALL
    env_file:
      - .env.production
  db:
    image: mariadb:latest
    user: mysql:mysql
    ports:
      - 3306:3306/tcp
    env_file:
      - .env.production
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: